import './globals.css';
import Navigation from '@/components/navigation.js';
import Footer from '@/components/footer.js';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white">
        <Navigation className="py-3"/>
        {children}
        <Footer />
      </body>
    </html>
  )
}
