import Image from 'next/image';
import {getAllCustomers} from '@/components/getData.js'; 
import Link from 'next/link';
import Navigation from '@/components/navigation.js';
import Footer from '@/components/footer.js';

export const metadata = {
    title: 'Customers',
    description: 'Generated by create next app',
}

export default async function CustomerPage( {params} ) {
  
    const data = await getAllCustomers();
    const url = process.env.NEXT_PUBLIC_URL;
    
    return (
      <>
      <Navigation />  
      <main className="container mx-auto py-5">
        <h1 className="font-bold text-5xl mb-8">Customers</h1>
        <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
          {data.map( (customer) => (
            <Link href={`/customer/${customer.id}`} key={customer.id}>
            <div className="flex flex-col p-2 border-solid border-4 border-gray-200 hover:border-gray-400 gap-5">
                <div className="flex flex-row items-center">    
                    <Image
                    className="mr-2 rounded-full"
                    src={customer.avatar}
                    width="100"
                    height="100"
                    alt={customer.name}
                    />
                <   h2 className="font-bold text-2xl p-3">{customer.name}</h2>
              </div>
              <div>
                <p>{customer.age * 10}</p>
                <p>{customer.address}</p>
                <p className="font-bold">{customer.city}</p>
              </div>  
            </div>
            </Link>
          ))}
        </section>
      </main>
      <Footer />
      </>
    )
  }